export type DocType = "idea" | "solution";
export type IdeaStatus = "open" | "in_progress" | "solved";
export type ArtifactType = "prompt" | "skill" | "automation";
export type DatasetVariant = "pre" | "post";

export interface UserRecord {
  id: string;
  name: string;
  /** Service line. Labelled "Service" in the UI; `service` below is "Sub-service". */
  org: string;
  service: string;
  manager_id: string | null;
  /**
   * Synthetic contact address on the reserved `gbs.example` TLD, generated by
   * scripts/generate-seed.ts from the display name. Reserved means it cannot
   * resolve, so the app can ship real mailto links without any address in this
   * repo ever reaching a real inbox.
   */
  email: string;
}

export interface DuplicateCandidate {
  id: string;
  score: number;
}

export interface IdeaRecord {
  id: string;
  doc_type: "idea";
  /** Service line. Labelled "Service" in the UI; `service` below is "Sub-service". */
  org: string;
  service: string;
  title: string;
  description: string;
  notes: string;
  submitted_by: string;
  submitted_by_manager: string;
  submitted_date: string;
  status: IdeaStatus;
  linked_solution_id: string | null;
  duplicate_of: string | null;
  duplicate_candidates: DuplicateCandidate[];

  // Enrichment fields — empty in the pre-enrichment dataset.
  has_solution: boolean;
  solution_link: string | null;
  solution_summary: string | null;
  solution_tags: string[];

  embedding: number[];
}

export interface SolutionRecord {
  id: string;
  doc_type: "solution";
  resolves_idea_id: string | null;
  name: string;
  artifact_type: ArtifactType;
  /**
   * Underlying tool/platform used to build the solution — distinct from
   * artifact_type, which describes the kind of artifact. Fixed list, set at
   * record-creation time (never LLM-inferred at enrichment):
   * "ChatGPT" | "Claude" | "AI + RPA" | "AI + local automation" |
   * "Local automation" | "RPA" | "Process improvement" | "Other"
   */
  technology_type: string;
  raw_description: string;
  ai_generated_summary: string | null;
  category_tags: string[];
  artifact_link: string;
  solution_owner: string;
  built_by: string;
  date_built: string;
  date_last_reviewed: string | null;
  duplicate_of: string | null;
  duplicate_candidates: DuplicateCandidate[];

  embedding: number[];
}

export type CatalogRecord = IdeaRecord | SolutionRecord;

export interface DatasetMeta {
  variant: DatasetVariant;
  generated_at: string;
  embedding_model: string;
  duplicate_threshold: number;
}

export interface Dataset extends DatasetMeta {
  ideas: IdeaRecord[];
  solutions: SolutionRecord[];
}

/** A record as sent to the browser — embeddings and raw user ids are stripped/replaced for payload size and readability. */
export interface ClientIdea
  extends Omit<IdeaRecord, "embedding" | "submitted_by" | "submitted_by_manager"> {
  submitted_by_name: string;
  submitted_by_manager_name: string;
  /** Synthetic contact addresses, null when the user id does not resolve. */
  submitted_by_email: string | null;
  submitted_by_manager_email: string | null;
}

export interface ClientSolution
  extends Omit<SolutionRecord, "embedding" | "solution_owner" | "built_by"> {
  solution_owner_name: string;
  built_by_name: string;
  solution_owner_email: string | null;
  built_by_email: string | null;
}

export type ClientRecord = ClientIdea | ClientSolution;

export interface ScoredResult<R = CatalogRecord> {
  record: R;
  /** Cosine similarity between the query embedding and this record's embedding. */
  score: number;
  /** True when this result is present because of the retrieval-time cross-reference join, not its own rank. */
  via_link: boolean;
  /** The id of the paired record (idea ↔ solution), when one exists. */
  linked_id: string | null;
}

/** Scored result as serialized to the browser (embeddings stripped, names resolved). */
export type ClientScoredResult = ScoredResult<ClientRecord>;

/**
 * One card on the Kanban board (v3 §0 — the board is the only layout, serving
 * both browse and search). Browse mode has no query, so score/via_link are
 * absent and the card renders no match label. ClientScoredResult is
 * structurally assignable to this.
 */
export interface BoardItem {
  record: ClientRecord;
  score?: number;
  via_link?: boolean;
}

// The old SearchApiResponse was removed in v4.6 along with /api/search. The
// one retrieval route's payload is CheckApiResponse in lib/overlap.ts, which
// carries these same ranked sets alongside the verdict.
